### PR TITLE
Created json2acl.juniper.py file

### PR DESCRIPTION
**Pull request by pliviu**
Python3 script to generate juniper firewall from json (without including size of packets, for the moment).

### CODE REVIEW

**Review by de-cix-role — CHANGES_REQUESTED** [review]
Hey, that was fast ;) I really recommend including the packet sizes. It's crucial to avoid false positives, especially with respect to DNS.

**Comment by pliviu** [comment]
Added size to juniper firewall!

**Comment by pliviu** [comment]
Added suport for python 2

**Comment by pliviu** [comment]
> Hey, that was fast ;) I really recommend including the packet sizes. It's crucial to avoid false positives, especially with respect to DNS.

Packet size support is already added. Is there any other changes to add?

**Comment by de-cix-role** [comment]
Have you tested the generated results with a Juniper CLI?

**Comment by pliviu** [comment]
> Have you tested the generated results with a Juniper CLI?

Of course!
[juniper.output.txt](https://github.com/DE-CIX/ripe84-learning-acls/files/8762067/juniper.output.txt)

**Comment by de-cix-role** [comment]
Thank you for sending the output. I see you are not treating exclusion sets correctly. The notation ~{1,2,3} has the semantics of "not any of these". I'm not sure if this is supported by Juniper. Usually these are attacks based on port spraying (i.e., using random source ports), so it is save to replace with a wildcard, if negating lists does not work.

I also realized that you do not treat dst/src_port == (0, 0) correctly, those are fragments.

**Comment by pliviu** [comment]
> Thank you for sending the output. I see you are not treating exclusion sets correctly. The notation ~{1,2,3} has the semantics of "not any of these". I'm not sure if this is supported by Juniper. Usually these are attacks based on port spraying (i.e., using random source ports), so it is save to replace with a wildcard, if negating lists does not work.
> 
> I also realized that you do not treat dst/src_port == (0, 0) correctly, those are fragments.

Fixed ports/protocols exception.
I didn't notice dst/src_port == (0, 0) in json; i'll double check the readme for fragmented packets and fix this also.
[juniper.output2.txt](https://github.com/DE-CIX/ripe84-learning-acls/files/8772345/juniper.output2.txt)

**Comment by de-cix-role** [comment]
@pliviu do you need any further assistance?

**Pull request closed without merging**
